// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: myfirstproto.proto

package go_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define messages
// Messages descripes the types of arguments (abstract data structures) we can use in the above rpc methods
// The number that each field is set equal to, is simply an identifier and...
// ...thus its value doesn't matter as long as it's different for every field in a message structure.
type Textk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Textk) Reset() {
	*x = Textk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myfirstproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Textk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Textk) ProtoMessage() {}

func (x *Textk) ProtoReflect() protoreflect.Message {
	mi := &file_myfirstproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Textk.ProtoReflect.Descriptor instead.
func (*Textk) Descriptor() ([]byte, []int) {
	return file_myfirstproto_proto_rawDescGZIP(), []int{0}
}

func (x *Textk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WordCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word  string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *WordCount) Reset() {
	*x = WordCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myfirstproto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCount) ProtoMessage() {}

func (x *WordCount) ProtoReflect() protoreflect.Message {
	mi := &file_myfirstproto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCount.ProtoReflect.Descriptor instead.
func (*WordCount) Descriptor() ([]byte, []int) {
	return file_myfirstproto_proto_rawDescGZIP(), []int{1}
}

func (x *WordCount) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WordCountList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// When compiled, names of generated types are in camelCase.
	WordCounts []*WordCount `protobuf:"bytes,17,rep,name=word_counts,json=wordCounts,proto3" json:"word_counts,omitempty"`
}

func (x *WordCountList) Reset() {
	*x = WordCountList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myfirstproto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordCountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCountList) ProtoMessage() {}

func (x *WordCountList) ProtoReflect() protoreflect.Message {
	mi := &file_myfirstproto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCountList.ProtoReflect.Descriptor instead.
func (*WordCountList) Descriptor() ([]byte, []int) {
	return file_myfirstproto_proto_rawDescGZIP(), []int{2}
}

func (x *WordCountList) GetWordCounts() []*WordCount {
	if x != nil {
		return x.WordCounts
	}
	return nil
}

var File_myfirstproto_proto protoreflect.FileDescriptor

var file_myfirstproto_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x79, 0x66, 0x69, 0x72, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x05, 0x54, 0x65, 0x78, 0x74, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x35, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0b, 0x77, 0x6f, 0x72,
	0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x32, 0x67, 0x0a, 0x13, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x25, 0x0a,
	0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x06, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x6b, 0x1a, 0x0e, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x12,
	0x0a, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x57, 0x6f,
	0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x42,
	0x16, 0x5a, 0x14, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x31, 0x2f, 0x67, 0x6f,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myfirstproto_proto_rawDescOnce sync.Once
	file_myfirstproto_proto_rawDescData = file_myfirstproto_proto_rawDesc
)

func file_myfirstproto_proto_rawDescGZIP() []byte {
	file_myfirstproto_proto_rawDescOnce.Do(func() {
		file_myfirstproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_myfirstproto_proto_rawDescData)
	})
	return file_myfirstproto_proto_rawDescData
}

var file_myfirstproto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_myfirstproto_proto_goTypes = []interface{}{
	(*Textk)(nil),         // 0: Textk
	(*WordCount)(nil),     // 1: WordCount
	(*WordCountList)(nil), // 2: WordCountList
}
var file_myfirstproto_proto_depIdxs = []int32{
	1, // 0: WordCountList.word_counts:type_name -> WordCount
	0, // 1: FrequencyCalculator.Calculate:input_type -> Textk
	1, // 2: FrequencyCalculator.Combine:input_type -> WordCount
	2, // 3: FrequencyCalculator.Calculate:output_type -> WordCountList
	2, // 4: FrequencyCalculator.Combine:output_type -> WordCountList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_myfirstproto_proto_init() }
func file_myfirstproto_proto_init() {
	if File_myfirstproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myfirstproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Textk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myfirstproto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myfirstproto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordCountList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myfirstproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myfirstproto_proto_goTypes,
		DependencyIndexes: file_myfirstproto_proto_depIdxs,
		MessageInfos:      file_myfirstproto_proto_msgTypes,
	}.Build()
	File_myfirstproto_proto = out.File
	file_myfirstproto_proto_rawDesc = nil
	file_myfirstproto_proto_goTypes = nil
	file_myfirstproto_proto_depIdxs = nil
}
