# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myfirstproto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12myfirstproto.proto\"\x15\n\x05Textk\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\tWordCount\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"0\n\rWordCountList\x12\x1f\n\x0bword_counts\x18\x11 \x03(\x0b\x32\n.WordCount2g\n\x13\x46requencyCalculator\x12%\n\tCalculate\x12\x06.Textk\x1a\x0e.WordCountList\"\x00\x12)\n\x07\x43ombine\x12\n.WordCount\x1a\x0e.WordCountList\"\x00(\x01\x42\x16Z\x14go_server1/go_protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myfirstproto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024go_server1/go_protos'
  _globals['_TEXTK']._serialized_start=22
  _globals['_TEXTK']._serialized_end=43
  _globals['_WORDCOUNT']._serialized_start=45
  _globals['_WORDCOUNT']._serialized_end=85
  _globals['_WORDCOUNTLIST']._serialized_start=87
  _globals['_WORDCOUNTLIST']._serialized_end=135
  _globals['_FREQUENCYCALCULATOR']._serialized_start=137
  _globals['_FREQUENCYCALCULATOR']._serialized_end=240
# @@protoc_insertion_point(module_scope)
